namespace OpenGarrison.Core;

public sealed record ExperimentalGameplaySettings(
    bool EnableSecondaryAbilities = true,
    bool EnableSoldierFastCapture = false,
    bool EnableDemoknightFastCapture = false,
    bool EnableDemoknightKit = false,
    bool EnableCapturedPointHealingAura = false,
    bool EnableSoldierShotgunSecondaryWeapon = false,
    bool EnableSoldierShotgunLtdPerk = false,
    bool EnableSoldierAmmoRegeneratesWhileSwappedOut = false,
    bool EnableSoldierStingerRockets = false,
    bool EnableSoldierInfiniteAmmoDuringRage = false,
    bool EnableSoldierRageExtensionOnKill = false,
    bool EnableSoldierRageCaptureLockout = false,
    bool EnableSoldierRageCaptureDuringRage = false,
    bool EnableSoldierNapalmRockets = false,
    bool EnableSoldierFinalClipRocketBurst = false,
    bool EnableSoldierCivilDefenseTurret = false,
    bool EnableSoldierLuckyBastard = false,
    bool EnableSoldierThundergunner = false,
    bool EnableSoldierBattleborn = false,
    bool EnableSoldierFogOfWar = false,
    bool EnableEngineerGuardianMatrix = false,
    bool EnableEngineerIncendiaryEnhancements = false,
    bool EnableEngineerCryonicMunitions = false,
    bool EnableEngineerAutonomousPhaseEngine = false,
    bool EnableEngineerOutputInducer = false,
    bool EnableEngineerEssenceExtractor = false,
    bool EnableEngineerCooperativeTargetingHarness = false,
    bool EnableEngineerRegenerativeDiode = false,
    bool EnableEngineerOsmosisConductor = false,
    bool EnableEngineerAmperageAccelerator = false,
    bool EnableEngineerHardwareHardener = false,
    bool EnableEngineerCaveatInjector = false,
    bool EnableEngineerPrecisionInstantiator = false,
    bool EnableEngineerBuckshotConversion = false,
    bool EnableEngineerIntegrityProjector = false,
    bool EnableEngineerMisdirectionField = false,
    bool EnableEngineerConfusionField = false,
    bool EnableEngineerGravitonAffixer = false,
    bool EnableEngineerAuraEnergizer = false,
    bool EnableEngineerEntanglementTraverser = false,
    bool EnableEngineerAlchemicalAnode = false,
    bool EnableEngineerExperimentalOverkillAugment = false,
    bool EnableEngineerEfficiencyStabilizer = false,
    bool EnableEngineerMateriaRecycler = false,
    bool EnableEngineerDestinyPunctuator = false,
    bool EnableEngineerFreezeRay = false,
    bool EnableSoldierDangerClose = false,
    bool EnableHealOnDamage = false,
    bool EnableHealOnKill = false,
    bool EnableSelfDamageHealing = false,
    bool EnableRage = false,
    bool EnableRateOfFireMultiplierOnDamage = false,
    bool EnableSoldierInstantReload = false,
    bool EnableSpeedOnDamage = false,
    bool EnableSpeedOnKill = false,
    bool EnablePassiveHealthRegeneration = false,
    bool EnableInvincibilityOnKill = false,
    bool EnableGhostPhaseOnKill = false,
    bool EnableProjectileSpeedMultiplier = false,
    bool EnableAirshotDamageMultiplier = false,
    bool EnableComboTracking = false,
    bool EnableKillStreakTracking = false,
    bool EnableEnemyHealthPackDrops = false,
    bool EnableEnemyDroppedWeapons = false,
    bool EnablePracticeBotsPrioritizeKills = false,
    float EnemyHealthPackDropChance = 0.1f,
    float HealOnDamageFraction = 0.35f,
    int HealOnKillAmount = 25,
    float KillInvincibilityDurationSeconds = 0.5f,
    float PassiveHealthRegenerationPerSecond = 3f,
    float ProjectileSpeedMultiplierValue = 1.2f,
    float AirshotDamageMultiplierValue = 1.25f,
    float ReloadSpeedMultiplierValue = 1f,
    float PassiveMovementSpeedMultiplier = 1f,
    float PassiveJumpHeightMultiplier = 1f,
    int PassiveBonusAirJumps = 0,
    float PassiveEvasionChance = 0f,
    float PassiveThornsFraction = 0f,
    float PassiveDamageResistance = 0f,
    float PassiveDamageMultiplier = 1f,
    float PassiveBulletDamageMultiplier = 1f,
    float PassiveExplosiveDamageMultiplier = 1f,
    float PassiveBulletResistance = 0f,
    float PassiveExplosiveResistance = 0f,
    float PassiveFireResistance = 0f,
    PlayerClass? PassiveDamageTargetClassId = null,
    float PassiveDamageToTargetClassMultiplier = 1f,
    float AcquiredWeaponDamageMultiplier = 1f,
    float AcquiredWeaponHealingMultiplier = 1f,
    int BonusProjectilesPerShot = 0,
    int SoldierShotgunPelletMultiplier = 1,
    float DemoknightSwordRangeMultiplier = 1f,
    int DemoknightSwordBaseDamage = 42,
    float DemoknightSwordDamageMultiplier = 1f,
    float DemoknightSwordCooldownMultiplier = 1f,
    float DemoknightChargeRechargeMultiplier = 1f,
    float DemoknightChargeDamageTakenMultiplier = 1f,
    bool EnableFullHealOnKill = false,
    bool EnableDemoknightPostRageRegeneration = false,
    bool EnableDemoknightFullControlDuringCharge = false,
    bool EnableDemoknightGhostDash = false,
    bool DisableSelfDamage = false,
    bool EnableFriendlyExplosionBoost = true,
    bool EnableFriendlyAirblastKnockback = false,
    bool EnableFriendlyAirburstKnockback = true)
{
    public const float CapturedPointHealingPerSecond = 8f;
    public const float DefaultEnemyHealthPackDropChance = 0.1f;
    public const float DefaultHealOnDamageFraction = 0.35f;
    public const int DefaultHealOnKillAmount = 25;
    public const float DefaultPassiveHealthRegenerationPerSecond = 3f;
    public const float RageMaxCharge = 500f;
    public const float RageDamageDealtChargeMultiplier = 1f;
    public const float RageDamageReceivedChargeMultiplier = 1f;
    public const float RageDurationSeconds = 7f;
    public const float SpeedBoostMultiplier = 1.2f;
    public const float RateOfFireCooldownMultiplier = 0.8f;
    public const float OnDamageBuffDurationSeconds = 2.5f;
    public const float OnKillBuffDurationSeconds = 3f;
    public const float DefaultKillInvincibilityDurationSeconds = 0.5f;
    public const float DefaultPassiveMovementSpeedMultiplier = 1f;
    public const float DefaultPassiveJumpHeightMultiplier = 1f;
    public const float DefaultDemoknightSwordRangeMultiplier = 1f;
    public const int DefaultDemoknightSwordBaseDamage = 42;
    public const float DefaultDemoknightSwordDamageMultiplier = 1f;
    public const float DefaultDemoknightSwordCooldownMultiplier = 1f;
    public const float DefaultDemoknightChargeRechargeMultiplier = 1f;
    public const float DefaultDemoknightChargeDamageTakenMultiplier = 1f;
    public const float DefaultProjectileSpeedMultiplier = 1.2f;
    public const float DefaultAirshotDamageMultiplier = 1.25f;
    public const float DefaultReloadSpeedMultiplier = 1f;
    public const float DefaultSoldierStingerRocketSpeedMultiplier = 0.3f;
    public const float DefaultSoldierStingerRocketTurnRateDegrees = 7.5f;
    public const float DefaultSoldierStingerDamageMultiplier = 2f;
    public const float DefaultSoldierStingerBlastRadiusMultiplier = 1.6f;
    public const float DefaultSoldierStingerBurstSpeedMultiplier = 2f;
    public const float DefaultSoldierStingerManualDetonationSelfKnockbackMultiplier = 3f;
    public const float DefaultSoldierRageExtensionSecondsPerKill = 2f;
    public const float DefaultDangerCloseBlastRadius = 72f;
    public const float DefaultDangerCloseExplosionDamage = 34f;
    public const float DefaultDangerCloseKnockbackPerTick = 7f;
    public const float DefaultDemoknightPostRageRegenerationPerSecond = 35f;
    public const float DefaultDemoknightPostRageRegenerationDurationSeconds = 10f;
    public const float DefaultSoldierCriticalInvincibilityDurationSeconds = 3f;
    public const float DefaultSoldierNapalmAfterburnIntensity = 1.2f;
    public const float DefaultSoldierNapalmAfterburnDurationSourceTicks = 90f;
    public const float DefaultSoldierNapalmGravityMultiplier = 1.45f;
    public const float DefaultSoldierFinalRocketDamageMultiplier = 1.25f;
    public const float DefaultSoldierLuckyBastardInvincibilityDurationSeconds = 5f;
    public const int DefaultSoldierLuckyBastardMinimumKills = 3;
    public const float DefaultSoldierFogOfWarInitialEvasionChance = 0.02f;
    public const float DefaultSoldierFogOfWarWindowSeconds = 3f;
    public const int DefaultSoldierCivilDefenseTurretDeployCooldownTicks = 30;
    public const int DefaultSoldierThundergunnerCooldownTicks = 24;
    public const float DefaultSoldierThundergunnerEmptyClipForceMultiplier = 2f;
    public const float DefaultGhostDashDurationSeconds = 0.5f;
    public const float DefaultGhostDashCooldownSeconds = 1f;
    public const float DefaultGhostDashNextAttackDamageMultiplier = 1.4f;
    public const float DefaultGhostDashSlideVelocityPerTick = 1.25f;
    public const float HeavyGhostDashDurationSeconds = DefaultGhostDashDurationSeconds * 0.5f;
    public const float HeavyGhostDashSpeedMultiplier = 1.4f;
    public const float HeavyGhostDashMovementDurationSeconds = (DefaultGhostDashDurationSeconds * 1.5f) / HeavyGhostDashSpeedMultiplier;
    public const float HeavyGhostDashCooldownSeconds = 12f;
    public const float HeavyGhostDashImpulseScale = 1f;
    public const float HeavyGhostDashSlideVelocityPerTick = 3f;
    public const float HeavyGhostDashBurstSpeedMultiplier = 4f;
    public const bool HeavyGhostDashDisableGravityDefault = true;
    public const bool HeavyGhostDashEnableGhostTrailDefault = true;
    public const int DefaultEngineerGuardianMatrixSentryBonusHealth = 100;
    public const float DefaultEngineerIncendiaryEnhancementsCloseRange = 118f;
    public const float DefaultEngineerIncendiaryEnhancementsBurnDurationSourceTicks = 75f;
    public const float DefaultEngineerIncendiaryEnhancementsBurnIntensity = 1.9f;
    public const int DefaultEngineerIncendiaryEnhancementsFlameCount = 2;
    public const float DefaultEngineerIncendiaryEnhancementsFlameSpeed = 6.25f;
    public const float DefaultEngineerCryonicMunitionsSlowMovementMultiplier = 0.55f;
    public const int DefaultEngineerCryonicMunitionsFreezeHitCount = 3;
    public const float DefaultEngineerCryonicMunitionsFreezeDurationSeconds = 3f;
    public const float DefaultEngineerCryonicMunitionsSlowRefreshSeconds = 0.45f;
    public const float DefaultEngineerAutonomousPhaseEngineHoverHeight = 32f;
    public const float DefaultEngineerAutonomousPhaseEngineFollowDistance = 42f;
    public const float DefaultEngineerAutonomousPhaseEngineFollowSpeedPerTick = 3.6f;
    public const float DefaultEngineerGuardianMatrixShieldHealth = 200f;
    public const float DefaultEngineerNearbySentryAuraRadius = 112f;
    public const float DefaultEngineerRegenerativeDiodeHealthPerSecond = 5f;
    public const int DefaultEngineerOutputInducerAdditionalSentries = 1;
    public const float DefaultEngineerEssenceExtractorDrainPerSecond = 25f;
    public const float DefaultEngineerEssenceExtractorVulnerabilityMultiplier = 1.3f;
    public const float DefaultEngineerEssenceExtractorDebuffSeconds = 1.2f;
    public const float DefaultEngineerEssenceExtractorSlowMovementMultiplier = 0.2f;
    public const float DefaultEngineerEssenceExtractorSlowRefreshSeconds = 0.2f;
    public const float DefaultEngineerEssenceExtractorHealingChunkSize = 20f;
    public const float DefaultEngineerCooperativeTargetingHarnessDamageMultiplier = 1.35f;
    public const float DefaultEngineerAmperageAcceleratorMaxRateOfFireMultiplier = 3f;
    public const int DefaultEngineerAmperageAcceleratorShotsToMax = 16;
    public const float DefaultEngineerAmperageAcceleratorResetSeconds = 3f;
    public const int DefaultEngineerHardwareHardenerSentryBonusHealth = 200;
    public const float DefaultEngineerHardwareHardenerDamageResistance = 0.3f;
    public const int DefaultEngineerCaveatInjectorShotInterval = 5;
    public const int DefaultEngineerCaveatInjectorRocketCount = 3;
    public const float DefaultEngineerCaveatInjectorRocketSpeed = 5.5f;
    public const float DefaultEngineerCaveatInjectorRocketRenderScale = 0.55f;
    public const float DefaultEngineerCaveatInjectorRocketLockDelaySeconds = 1f;
    public const float DefaultEngineerCaveatInjectorPostLockSpeedMultiplier = 2f;
    public const float DefaultEngineerCaveatInjectorSpreadDegrees = 12f;
    public const float DefaultEngineerCaveatInjectorRocketTurnRateDegrees = 18f;
    public const int DefaultEngineerCaveatInjectorDirectHitDamage = 18;
    public const float DefaultEngineerCaveatInjectorExplosionDamage = 21f;
    public const float DefaultEngineerCaveatInjectorBlastRadius = 35f;
    public const float DefaultEngineerPrecisionInstantiatorReloadMultiplier = 2.5f;
    public const int DefaultEngineerPrecisionInstantiatorDamage = 85;
    public const float DefaultEngineerBuckshotConversionReloadMultiplier = 1f / 0.65f;
    public const float DefaultEngineerBuckshotConversionPelletMultiplier = 1.4f;
    public const float DefaultEngineerIntegrityProjectorRadius = 84f;
    public const float DefaultEngineerMisdirectionFieldEvasionChance = 0.6f;
    public const float DefaultEngineerConfusionFieldAuraRadius = 132f;
    public const float DefaultEngineerConfusionFieldTargetLockSeconds = 2.5f;
    public const float DefaultEngineerConfusionFieldRetaliationSeconds = 7f;
    public const float DefaultEngineerGravitonAffixerEnemySlowMovementMultiplier = 0.55f;
    public const float DefaultEngineerGravitonAffixerEnemySlowDurationSeconds = 1.25f;
    public const float DefaultEngineerGravitonAffixerPullDurationSeconds = 3f;
    public const float DefaultEngineerGravitonAffixerPullRadius = 132f;
    public const float DefaultEngineerGravitonAffixerPullImpulsePerTick = 2.4f;
    public const float DefaultEngineerAuraEnergizerAuraRadius = 112f;
    public const float DefaultEngineerAuraEnergizerAuraMovementSpeedMultiplier = 1.3f;
    public const float DefaultEngineerAuraEnergizerBurstMovementSpeedMultiplier = 2f;
    public const float DefaultEngineerAuraEnergizerBurstDurationSeconds = 2.5f;
    public const float DefaultEngineerAuraEnergizerJumpBoostHeightReductionFraction = 0.6f;
    public const float DefaultEngineerAlchemicalAnodeHealingFraction = 0.2f;
    public const float DefaultEngineerEfficiencyStabilizerMovementSpeedPerMetal = 0.01f;
    public const float DefaultEngineerMateriaRecyclerBonusMaxMetal = 100f;
    public const float DefaultEngineerMateriaRecyclerMetalPerDamage = 1f;
    public const int DefaultEngineerDestinyPunctuatorBonusMaxHealth = 100;
    public const float DefaultEngineerDestinyPunctuatorHealthPackHealingMultiplier = 1.5f;
    public const int DefaultEngineerDestinyPunctuatorShotgunClipSize = 2;
    public const int DefaultEngineerDestinyPunctuatorSecondaryShellCost = 2;
    public const int DefaultEngineerDestinyPunctuatorPelletMultiplier = 3;
    public const float DefaultEngineerDestinyPunctuatorSpreadMultiplier = 1.3f;
    public const float DefaultEngineerDestinyPunctuatorSelfKnockbackPerTick = 13f;
    public const int DefaultEngineerExperimentalOverkillAugmentRocketCount = 2;
    public const float DefaultEngineerExperimentalOverkillAugmentRocketSpreadDegrees = 7f;
    public const float DefaultEngineerFreezeRayDamagePerSecond = 20f;
    public const float DefaultEngineerFreezeRaySlowMovementMultiplier = 0.45f;
    public const float DefaultEngineerFreezeRaySlowRefreshSeconds = 0.2f;
    public const float DefaultEngineerFreezeRayFreezeDelaySeconds = 2f;
    public const float DefaultEngineerFreezeRayExposureWindowSeconds = 4f;
    public const float DefaultEngineerFreezeRayAttackCycleMultiplier = 2.5f;
    public const float DefaultEngineerFreezeRayOutgoingDamageMultiplier = 0.6f;
    public const int DefaultEngineerFreezeRayTargetCount = 3;
    public const float DefaultEngineerFreezeRayChainRadius = 78f;
    public const float ComboTimeoutSeconds = 6f;
    public const float KritzCriticalDamageMultiplier = 3f;
    public const float MultiKillWindowSeconds = 3f;
    public const float EnemyHealthPackLargeChance = 0.5f;
    public const float EnemyDroppedWeaponChance = 0.5f;
}
